name: Deploy Docker

on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Docker Login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Push Image to Docker Hub
        run: |
          docker build -t simba1330/sacra-story-api:latest .
          docker push simba1330/sacra-story-api:latest
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker pull simba1330/sacra-story-api
            docker stop tetu || true
            docker rm tetu || true
            docker run -d -p 8080:8080 --name tetu \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_USERNAME=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
            -e DB_PORT=${{ secrets.DB_PORT }} \
            -e DB_TYPE=${{ secrets.DB_TYPE }} \
            -e PORT=${{ secrets.PORT }} \
            simba1330/sacra-story-api
      - name: Send Telegram Notification
        if: success()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: Success deploy
